# Generated by Django 6.0.2 on 2026-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('secretary', 'Secretary'), ('stock_manager', 'Stock Manager'), ('employee', 'Employee')], default='employee', help_text='Access level the invitee will have once they accept.', max_length=20),
        ),
    ]
