# Generated by Django 6.0.2 on 2026-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('XAF', 'FCFA — Central Africa (XAF)'), ('XOF', 'FCFA — West Africa (XOF)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('ZAR', 'South African Rand (R)'), ('CAD', 'Canadian Dollar (CA$)')], default='XAF', help_text='Currency used for all prices displayed across the application.', max_length=3),
        ),
    ]
