# Generated by Django 6.0.2 on 2026-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='How many units of your selected currency equal 1 USD (e.g. 600 for XAF). Every amount is stored in USD; this rate is applied only when displaying it. Update it yourself whenever the real rate changes — not fetched automatically.', max_digits=14),
        ),
    ]
