# Generated by Django 6.0.2 on 2026-10-07 18:23

from django.db import migrations, models

# Mirrors Company.CURRENCY_CHOICES at the time this migration was written —
# intentionally hardcoded rather than imported, since historical migration
# models don't carry class-level attributes like CURRENCY_CHOICES.
CURRENCY_CODES = ['XAF', 'XOF', 'USD', 'EUR', 'GBP', 'NGN', 'GHS', 'ZAR', 'CAD']


def seed_exchange_rates(apps, schema_editor):
    ExchangeRate = apps.get_model('accounts', 'ExchangeRate')
    ExchangeRate.objects.bulk_create([
        ExchangeRate(currency=code, rate=1) for code in CURRENCY_CODES
    ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XAF', 'FCFA — Central Africa (XAF)'), ('XOF', 'FCFA — West Africa (XOF)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('ZAR', 'South African Rand (R)'), ('CAD', 'Canadian Dollar (CA$)')], max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, default=1, help_text='Units of this currency equal to 1 USD.', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='exchange_rate',
        ),
        migrations.RunPython(seed_exchange_rates, noop),
    ]
