# Generated by Django 6.0.2 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_stock_quantity_gte_0'),
        ('marketplace', '0011_cartitem_cart_item_quantity_gte_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stock'),
        ),
    ]
