# Generated by Django 6.0.2 on 2026-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_invitation_role'),
        ('finance', '0005_marketplacefinancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='clientinvoice',
            unique_together={('company', 'invoice_number')},
        ),
    ]
