# Generated by Django 6.0.2 on 2026-10-07 15:37

import django.db.models.deletion
from django.db import migrations, models


def link_existing_invoices_forward(apps, schema_editor):
    """Best-effort link of existing invoices to a Supplier by matching name
    (created if missing) — supplier_name/address stay as the frozen snapshot."""
    SupplierInvoice = apps.get_model('finance', 'SupplierInvoice')
    Supplier = apps.get_model('suppliers', 'Supplier')

    supplier_cache = {}

    for invoice in SupplierInvoice.objects.exclude(supplier_name='').select_related('company'):
        name = invoice.supplier_name.strip()
        if not name:
            continue
        key = (invoice.company_id, name)
        supplier = supplier_cache.get(key)
        if supplier is None:
            supplier, _ = Supplier.objects.get_or_create(
                company_id=invoice.company_id,
                name=name,
                defaults={'address': invoice.supplier_address or ''},
            )
            supplier_cache[key] = supplier
        invoice.supplier = supplier
        invoice.save(update_fields=['supplier'])


def link_existing_invoices_backward(apps, schema_editor):
    pass  # supplier_name/address were never removed — nothing to restore


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_clientinvoice_invoice_number_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='suppliers.supplier'),
        ),
        migrations.RunPython(link_existing_invoices_forward, link_existing_invoices_backward),
    ]
