# Generated by Django 6.0.2 on 2026-09-25 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_mtn_momo_number_company_orange_money_number_and_more'),
        ('inventory', '0004_alter_stock_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_gte_0'),
        ),
    ]
