# Generated by Django 6.0.2 on 2026-10-07 15:37 — hand-edited to migrate data
# (see migrate_supplier_names_forward) instead of silently dropping it.

import django.db.models.deletion
from django.db import migrations, models


def migrate_supplier_names_forward(apps, schema_editor):
    Stock = apps.get_model('inventory', 'Stock')
    Supplier = apps.get_model('suppliers', 'Supplier')

    supplier_cache = {}  # (company_id, name) -> Supplier instance

    for stock in Stock.objects.exclude(supplier_name='').select_related('company'):
        name = stock.supplier_name.strip()
        if not name:
            continue
        key = (stock.company_id, name)
        supplier = supplier_cache.get(key)
        if supplier is None:
            supplier, _ = Supplier.objects.get_or_create(
                company_id=stock.company_id,
                name=name,
                defaults={'phone': stock.supplier_contact or ''},
            )
            supplier_cache[key] = supplier
        stock.supplier = supplier
        stock.save(update_fields=['supplier'])


def migrate_supplier_names_backward(apps, schema_editor):
    Stock = apps.get_model('inventory', 'Stock')

    for stock in Stock.objects.select_related('supplier'):
        if stock.supplier:
            stock.supplier_name = stock.supplier.name
            stock.supplier_contact = stock.supplier.phone
            stock.save(update_fields=['supplier_name', 'supplier_contact'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_stock_quantity_gte_0'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='suppliers.supplier'),
        ),
        migrations.RunPython(migrate_supplier_names_forward, migrate_supplier_names_backward),
        migrations.RemoveField(
            model_name='stock',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='supplier_name',
        ),
    ]
